### PR TITLE
Add url to AOC website

### PR DESCRIPTION
**Pull request by mrcaseb**
I am very lazy and need a clickable link to the aoc website of the current day in my Rmd file. 

This PR adds such a url. The url doesn't like the padded day so I had to add another gsub

### CODE REVIEW

**Comment by tanho63** [comment]
I think I’d actually prefer to have it as a CLI hyperlink provided when aoc_get is run, e.g. here: https://github.com/tanho63/aoc.elf/blob/master/R/aoc_get.R#L29 + something like https://cli.r-lib.org/reference/links.html

I was debating whether auto-open the browser actually…

**Comment by mrcaseb** [comment]
That link would get lost in the console sooner or later but we could do both AND auto-open a browser tab

**Comment by mrcaseb** [comment]
I would suggest something like this to view the website and print the url

```r
.aoc_view_problem <- function(year, day){
  url <- paste("https://adventofcode.com", year, "day", day, sep = "/")

  if (interactive()) {
    cli::cli_alert_info("Opening {.url {url}}")
    utils::browseURL(url)
  } else {
    cli::cli_alert_info("View problem at {.url {url}}")
  }
  invisible(url)
}
```

But I am unsure where it should be called. aoc_init? aoc_get?

**Comment by tanho63** [comment]
Probably inside get - you can't visit the page til after the midnight countdown

**Review by tanho63 — APPROVED** [review]
lgtm ty

**Pull request merged**
